"""Add Audio model

Revision ID: 08054f339640
Revises: 4e84f145e577
Create Date: 2024-03-28 18:57:08.545914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08054f339640'
down_revision = '4e84f145e577'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('url', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audio')
    # ### end Alembic commands ###
