"""Added Comment model

Revision ID: 20d99b11abf1
Revises: bb05921213a4
Create Date: 2023-10-17 19:22:48.995809

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20d99b11abf1"
down_revision = "bb05921213a4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "comment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("date_posted", sa.DateTime(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["author_id"], ["user.id"], name="fk_author_id"),
        sa.ForeignKeyConstraint(["post_id"], ["post.id"], name="fk_post_id"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("comment")
    # ### end Alembic commands ###
