"""Add status field to Post model

Revision ID: a9ab024209b0
Revises: a66d574d2e73
Create Date: 2024-10-15 16:53:11.644961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9ab024209b0'
down_revision = 'a66d574d2e73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Add 'status' column with default 'draft'
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False, server_default='draft'))

    # Update existing posts to have status 'published'
    op.execute("UPDATE post SET status = 'published'")

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('status', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop the 'status' column
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###