"""user profile picture

Revision ID: 4d40b524c6dd
Revises: ea99c3c43496
Create Date: 2023-10-29 18:57:04.608934

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4d40b524c6dd"
down_revision = "ea99c3c43496"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("profile_picture", sa.String(length=500), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("profile_picture")

    # ### end Alembic commands ###
