"""add hidden bool to Page

Revision ID: 54c54a006adb
Revises: 6521a827720d
Create Date: 2024-02-17 23:53:11.297063

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "54c54a006adb"
down_revision = "6521a827720d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("page", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "hidden", sa.Boolean(), nullable=False, server_default=sa.text("False")
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("page", schema=None) as batch_op:
        batch_op.drop_column("hidden")

    # ### end Alembic commands ###
