"""remove album model

Revision ID: 92cb4fa896b9
Revises: f8675f5347ed
Create Date: 2024-07-03 01:12:04.652325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92cb4fa896b9'
down_revision = 'f8675f5347ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('album')
    op.drop_table('track')
    op.drop_table('album_tracks')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('album_tracks',
    sa.Column('album_id', sa.INTEGER(), nullable=True),
    sa.Column('track_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['album.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['track.id'], )
    )
    op.create_table('track',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('duration', sa.VARCHAR(length=50), nullable=True),
    sa.Column('track_number', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('album',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=80), nullable=False),
    sa.Column('artist', sa.VARCHAR(length=80), nullable=False),
    sa.Column('release_date', sa.DATETIME(), nullable=False),
    sa.Column('cover_image', sa.VARCHAR(length=120), nullable=True),
    sa.Column('embed', sa.TEXT(), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
