"""Make Audio model date & url nullable

Revision ID: b1e8e89bf086
Revises: 08054f339640
Create Date: 2024-03-28 19:41:42.807688

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b1e8e89bf086"
down_revision = "08054f339640"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("audio", schema=None) as batch_op:
        batch_op.alter_column(
            "url", existing_type=sa.VARCHAR(length=200), nullable=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("audio", schema=None) as batch_op:
        batch_op.alter_column(
            "url", existing_type=sa.VARCHAR(length=200), nullable=False
        )

    # ### end Alembic commands ###
