"""Updated subscription model

Revision ID: b30e22f02ab5
Revises: 79c3538939ac
Create Date: 2023-07-25 12:40:10.236672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b30e22f02ab5'
down_revision = '79c3538939ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unsubscribe_token', sa.String(length=32), nullable=False))
        batch_op.add_column(sa.Column('interval', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('last_email_sent', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint('uix_email', ['email'])
        batch_op.create_unique_constraint('uix_unsubscribe_token', ['unsubscribe_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.drop_constraint('uix_unsubscribe_token', type_='unique')
        batch_op.drop_constraint('uix_email', type_='unique')
        batch_op.drop_column('last_email_sent')
        batch_op.drop_column('interval')
        batch_op.drop_column('unsubscribe_token')

    # ### end Alembic commands ###
