"""Add confirmed email bool to User model

Revision ID: e343223b3f53
Revises: 176ee623e9f8
Create Date: 2024-02-21 21:29:41.438883

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e343223b3f53"
down_revision = "176ee623e9f8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("confirmed", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("confirmed")

    # ### end Alembic commands ###
