"""post comments toggle

Revision ID: ea99c3c43496
Revises: 20d99b11abf1
Create Date: 2023-10-29 13:18:34.940687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea99c3c43496'
down_revision = '20d99b11abf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comments_enabled',
                                      sa.Boolean(),
                                      nullable=False,
                                      server_default=sa.sql.expression.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('comments_enabled')

    # ### end Alembic commands ###
