"""Add track_number to Track

Revision ID: f6113073d571
Revises: c7fbe453c43c
Create Date: 2023-09-07 18:02:45.108982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6113073d571'
down_revision = 'c7fbe453c43c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('date_updated',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('track', schema=None) as batch_op:
        batch_op.add_column(sa.Column('track_number', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track', schema=None) as batch_op:
        batch_op.drop_column('track_number')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('date_updated',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
