"""remove music archive audio model & album model

Revision ID: f8675f5347ed
Revises: c93ec1f418a5
Create Date: 2024-07-03 01:10:36.670903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8675f5347ed'
down_revision = 'c93ec1f418a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('music_archive_audio')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('music_archive_audio',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.Column('url', sa.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
